# Generated by Django 5.2.10 on 2026-01-20 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('duration', models.CharField(default='1m', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('Uso_CPU', 'Uso de CPU'), ('Uso_RAM', 'Uso de Memoria RAM')], max_length=50)),
                ('threshold', models.FloatField(help_text='Valor límite (%)')),
                ('duration_seconds', models.PositiveIntegerField(help_text='Tiempo mínimo en segundos')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=100)),
                ('operator', models.CharField(choices=[('>', '>'), ('<', '<'), ('>=', '>='), ('<=', '<='), ('==', '=='), ('!=', '!=')], max_length=2)),
                ('threshold', models.FloatField()),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='metrics.alert')),
            ],
        ),
        migrations.CreateModel(
            name='AlertLogic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', max_length=3)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alertlogic', to='metrics.alert')),
            ],
        ),
    ]
