groups:
- name: alerts
  rules:
  - alert: Prueba RAM
    expr: cpu_percent < 80.0
    for: 1m
    labels:
      severity: critical
      managed_by: django-admin
    annotations:
      summary: Alert Prueba RAM triggered
  - alert: Alerta unica RAM
    expr: 'memory_percent < 90.0'
    for: 10s
    labels:
      severity: warning
      managed_by: django-admin
    annotations:
      summary: Alert Alerta unica RAM triggered
