"""
Django settings for pruebatecno project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import logging
from pathlib import Path
from kombu import Queue, Exchange
from logging.handlers import RotatingFileHandler


BASE_DIR = Path(__file__).resolve().parent.parent

#Configuracion y definición de logs del sistema Django
LOG_DIR = Path(os.getenv("DJANGO_LOG_DIR", BASE_DIR / "logs"))
LOG_DIR.mkdir(parents=True, exist_ok=True)
LOG_FILE = os.getenv("DJANGO_LOG_FILE", str(LOG_DIR / "django.log"))
LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO").upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s (%(pathname)s:%(lineno)d)"
        },
        "simple": {
            "format": "%(asctime)s [%(levelname)s] %(message)s"
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": LOG_LEVEL,
            "formatter": "simple"
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_FILE,
            "maxBytes": 1024 * 1024 * 5,  # 5MB
            "backupCount": 5,
            "level": LOG_LEVEL,
            "formatter": "verbose"
        }
    },
    "root": {
        "handlers": ["console", "file"],
        "level": LOG_LEVEL
    }
}

NO_FILE_LOG = os.getenv("NO_FILE_LOG", "0") == "1"
if NO_FILE_LOG:
    # Quita el handler de archivo si no hay permisos
    if "file" in LOGGING.get("handlers", {}):
        LOGGING["handlers"].pop("file", None)
    # Deja solo consola en root handlers
    LOGGING["root"]["handlers"] = [h for h in LOGGING["root"]["handlers"] if h != "file"]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#rl06@ns24s%^=161x98j&3(!rd)#ukovgp-y0in4#x&wd8674'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    "http://localhost",
    "http://127.0.0.1",
]

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'http')

FORCE_SCRIPT_NAME = "/django"
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_extensions",
    "rest_framework",
    'django_prometheus',

    #Celery Stack
    'django_celery_beat',
    'django_celery_results',

    #apps propias
    'metrics',
    'api',
    #"monitoring",
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "metrics.middleware.InfluxMetricsMiddleware",
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'pruebatecno.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pruebatecno.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'pruebadb',
        'USER': 'admin',
        'PASSWORD': 'admin',
        'HOST': 'postgres',
        'PASSWORD': 'admin',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'django/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_FILES_DIRS = [BASE_DIR / "static"]

# ================================= Configuración de Celery ================================= 
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "django-db")

#Serialización de tareas con JSON para compatibilidad y seguridad
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = 'America/Santiago' #Ajuste de zona horaria para tareas con horas definidas
ENABLE_UTC = True

#Configuración de tiempo y warnings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 60 * 60  * 24 #Límite de 24 horas para tareas
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 60 * 23 #Límite de 23 horas de warning antes de forzar la terminación

#Retry en caso de fallo
CELERY_TASK_ACK_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1 
CELERY_REJECT_ON_WORKER_LOST = True

# Retry por defecto
CELERY_TASK_AUTORETRY_FOR = (Exception,)
CELERY_TASK_MAX_RETRIES = 5
CELERY_TASK_DEFAULT_RETRY_DELAY = 60  # Retraso de 1 minuto entre reintentos

#Rutas de tareas en cola
CELERY_TASK_ROUTES = {
    #Tareas de alta prioridad
    "pruebatecno.tasks.comprobar_sincronizacion": {
    "queue": "high_priority",
    "routing_key": "high_priority"
    },

    "pruebatecno.tasks.validar_integridad_alertas": {
    "queue": "high_priority",
    "routing_key": "high_priority"
    },

    #Tareas de prioridad baja
    "pruebatecno.tasks.recargar_reglas_prometheus": {
    "queue": "low_priority",
    "routing_key": "low_priority"
    },
}

# Resultados de tareas
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'default'
CELERY_RESULT_EXTENDED = True
CELERY_RESULT_EXPIRES = 3600 * 7 * 24  # Expiración de resultados en 24 horas

# Logs de Celery
CELERY_WORKER_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s] %(message)s'
CELERY_WORKER_TASK_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s] Task %(task_name)s[%(task_id)s]: %(message)s'

# BEAT Guardado de tareas periódicas en la base de datos para persistencia y administración desde Django Admin
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BEAT_SYNC_EVERY = 60 # Sincronización cada minuto para detectar cambios en tareas periódicas

#URL De Redis
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 20, "socket_connect_timeout": 5, "socket_timeout": 5},
        },
        "TIMEOUT": 300,  # 5 minutos
        "KEY_PREFIX": "pruebatecno"
    }
}

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

WHITENOISE_AUTOREFRESH = os.getenv("DJANGO_DEBUG", "False") == "True"
WHITENOISE_USE_FINDERS = True
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
